---
title: "Hw2"
author: "Getong Zhong"
date: "2023-02-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MVA)
```


## 2.1
```{R}
data("USairpollution", package = "HSAUR2")




for(i in seq(1, 7)){
  for(j in seq(i, 7)) {
    if (i != j) {
      bvbox(USairpollution[, c(i, j)], xlab=names(USairpollution)[i], ylab=names(USairpollution)[j])
      text(USairpollution[, c(i, j)][,1], USairpollution[, c(i, j)][,2], labels = rownames(USairpollution), cex = 0.7, pos = c(2, 2, 4, 2, 2))
      cor(USairpollution[, c(i, j)][,1],USairpollution[, c(i, j)][,2])
    }
  }
}

cor_set <- c()
for(i in seq(1, 7)){
  for(j in seq(i, 7)) {
    if (i != j) {
      c <- cor(USairpollution[, c(i, j)][,1],USairpollution[, c(i, j)][,2])
      cor_set = append(cor_set,c)
      
    }
  }
}
cor_set
```
## 2.2
Chi-square plot are usually used when the variables we are plotting are categorical, scatter plots can more directly show the correlationship between numeric variables.  
```{r}
compare <- function(data, i, j) {
  
  par(mfrow=c(1, 2))
  
  plot(data[[i]], data[[j]], xlab=names(data)[i], ylab=names(data[j]))
 
  chiplot(data[[i]], data[[j]])
  
}

compare(USairpollution, 1, 3)
```

## 2.3
I found the graph in 2.17 is more informative since it also shows us how the distribution looks like for each variables.
```{r}
measure <- structure(list(V1 = 1:20, V2 = c(34L, 37L, 38L, 36L, 38L, 43L,
                 40L, 38L, 40L, 41L, 36L, 36L, 34L, 33L, 36L, 37L, 34L, 36L, 38L,
                 35L), V3 = c(30L, 32L, 30L, 33L, 29L, 32L, 33L, 30L, 30L, 32L,
                 24L, 25L, 24L, 22L, 26L, 26L, 25L, 26L, 28L, 23L), V4 = c(32L,
                 37L, 36L, 39L, 33L, 38L, 42L, 40L, 37L, 39L, 35L, 37L, 37L, 34L,
                 38L, 37L, 38L, 37L, 40L, 35L)), .Names = c("V1", "V2", "V3",
                 "V4"), class = "data.frame", row.names = c(NA, -20L))
measure <- measure[,-1]
names(measure) <- c("chest", "waist", "hips")
measure$gender <- gl(2, 10)
levels(measure$gender) <- c("male", "female")



par(mfrow=c(3, 3))
for (i in seq(1,3)) {
  for (j in seq(1,3)) {
    if(i != j) {
      bvbox(measure[, c(i, j)])
    }
    else {
      boxplot(measure[[i]])
    }
  }
}
```
## 2.4

```{r}

par(mfrow=c(3, 3))
for (i in 1:3) {
  for (j in 1:3) {
    plot(measure[, i], measure[, j], xlab = names(measure)[i], ylab=names(measure)[j])
    if(i != j) {
      bvbox(measure[measure$gender == "male", c(i, j)], add=TRUE)
      bvbox(measure[measure$gender == "female", c(i, j)], add=TRUE)
    }
    points(measure[measure$gender == "male", c(i, j)], col="blue")
    points(measure[measure$gender == "female", c(i, j)], col="red")
  }
}

```
